In [36]:
import pandas as pd

df_2019 = pd.read_csv('model_2019.csv')
df_2018 = pd.read_csv('model_2018.csv')
df_2017 = pd.read_csv('model_2017.csv')

frames=[df_2017, df_2018, df_2019]
df = pd.concat(frames)
df.head()

,Unnamed: 0,Wine,Description,Vintage,Price,Score,Model Rating
0,0,Duckhorn Merlot Napa Valley Three Palms Vineyard-,"A powerful red, with concentrated flavors of r...",2014,$98,95.0,3
1,1,K Syrah Walla Walla Valley Powerline Estate-,"A knockout Syrah, precise and impeccably built...",2014,$45,95.0,3
2,2,Château Coutet Barsac-,"This shows the vivid, racy side of Barsac, wit...",2014,$37,96.0,3
3,3,Casanova di Neri Brunello di Montalcino-,"Effusive aromas and flavors of raspberry, cher...",2012,$65,95.0,3
4,4,Château de St.-Cosme Gigondas-,A textbook version of the brawny side of Gigon...,2015,$43,95.0,3

In [37]:
df = df.drop(columns=['Unnamed: 0'])
df.head()

,Wine,Description,Vintage,Price,Score,Model Rating
0,Duckhorn Merlot Napa Valley Three Palms Vineyard-,"A powerful red, with concentrated flavors of r...",2014,$98,95.0,3
1,K Syrah Walla Walla Valley Powerline Estate-,"A knockout Syrah, precise and impeccably built...",2014,$45,95.0,3
2,Château Coutet Barsac-,"This shows the vivid, racy side of Barsac, wit...",2014,$37,96.0,3
3,Casanova di Neri Brunello di Montalcino-,"Effusive aromas and flavors of raspberry, cher...",2012,$65,95.0,3
4,Château de St.-Cosme Gigondas-,A textbook version of the brawny side of Gigon...,2015,$43,95.0,3

In [38]:
df.dtypes

Wine             object
Description      object
Vintage          object
Price            object
Score           float64
Model Rating      int64
dtype: object

In [39]:
#Change price to an integer
df['Price'] = df['Price'].str[1:]
df.astype({'Price': 'int64'})
df.head()

,Wine,Description,Vintage,Price,Score,Model Rating
0,Duckhorn Merlot Napa Valley Three Palms Vineyard-,"A powerful red, with concentrated flavors of r...",2014,98,95.0,3
1,K Syrah Walla Walla Valley Powerline Estate-,"A knockout Syrah, precise and impeccably built...",2014,45,95.0,3
2,Château Coutet Barsac-,"This shows the vivid, racy side of Barsac, wit...",2014,37,96.0,3
3,Casanova di Neri Brunello di Montalcino-,"Effusive aromas and flavors of raspberry, cher...",2012,65,95.0,3
4,Château de St.-Cosme Gigondas-,A textbook version of the brawny side of Gigon...,2015,43,95.0,3

In [41]:
df.astype({'Price': 'int64'})

,Wine,Description,Vintage,Price,Score,Model Rating
0,Duckhorn Merlot Napa Valley Three Palms Vineyard-,"A powerful red, with concentrated flavors of r...",2014,98,95.0,3
1,K Syrah Walla Walla Valley Powerline Estate-,"A knockout Syrah, precise and impeccably built...",2014,45,95.0,3
2,Château Coutet Barsac-,"This shows the vivid, racy side of Barsac, wit...",2014,37,96.0,3
3,Casanova di Neri Brunello di Montalcino-,"Effusive aromas and flavors of raspberry, cher...",2012,65,95.0,3
4,Château de St.-Cosme Gigondas-,A textbook version of the brawny side of Gigon...,2015,43,95.0,3
...,...,...,...,...,...,...
95,Benanti Etna-,"A medium-bodied red, with a crisp tannic frame...",2017,28,90.0,3
96,Château Pichon Longueville Lalande Pauillac-,"Saturated with dark currant, fig and blackberr...",2016,197,97.0,3
97,Wine & Soul Douro Manoella-,Zesty currant and boysenberry notes are tangy ...,2016,22,90.0,3
98,Domaines Dominique Piron Morgon Côte du Py-,A vivid minerally undertone marks the pure ras...,2017,28,92.0,3
99,Domaine du Castel Grand Vin Haute-Judée-,"Ripe currant, blackberry and plum flavors are ...",2016,85,91.0,3

In [44]:
df.to_csv('model_combined')